name: "Terraform Deploy"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./terraform"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}

#name: "Terraform Deploy"
#on:
#  push:
#   branches:
#     - master
#jobs:
# terraform:
#  name: "Terraform"
#  runs-on: ubuntu-latest
#  steps:
#    - name: "Checkout"
#    uses: actions/checkout@master
#    - name: "Terraform Plan"
#    uses: hashicorp/terraform-github-actions@master
#    with: tf_actions_version: 0.12.13
#    tf_actions_subcommand: "plan"
#    tf_actions_working_dir: "./terraform"
#    tf_actions_comment: true
#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
#      TF_VAR_agent_client_secret: ${{secrets.TF_VAR_agent_client_secret }}
#      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
#      TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
#name: 'Terraform'
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#
#jobs:
#  terraform:
#    name: 'Terraform'
#    env:
#      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONS_ID }}
#      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#    runs-on: ubuntu-latest
#    environment: dev
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: 'Terraform Format'
#        uses: hashicorp/terraform-github-actions@v0.5.4
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'fmt'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform Init'
#        uses: hashicorp/terraform-github-actions@v0.5.4
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'init'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform plan'
#        uses: hashicorp/terraform-github-actions@v0.5.4
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'plan'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform Apply'
#        uses: hashicorp/terraform-github-actions@v0.5.4
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'apply'
#          tf_action_working_dir: "./terraform"


#name: 'Terraform'
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#
#jobs:
#  terraform:
#    name: 'Terraform'
#    env:
#      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONS_ID }}
#      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#    runs-on: ubuntu-latest
#    environment: dev
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: 'Terraform Format'
#        uses: hashicorp/terraform-github-actions@latest
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'fmt'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform Init'
#        uses: hashicorp/terraform-github-actions@latest
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'init'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform plan'
#        uses: hashicorp/terraform-github-actions@latest
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'plan'
#          tf_action_working_dir: "./terraform"
#      - name: 'Terraform Apply'
#        uses: hashicorp/terraform-github-actions@latest
#        with:
#          tf_actions_version: "0.15.0" # Adjust to the desired version
#          tf_action_subcommand: 'apply'
#          tf_action_working_dir: "./terraform"
#
##name: 'Terraform'
##
##on:
##  push:
##    branches:
##      - main
##  pull_request:
##
##jobs:
##  terraform:
##    name: 'Terraform'
##    env:
##      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
##      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
##      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONS_ID }}
##      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
##    runs-on: ubuntu-latest
##    environment: dev
##    defaults:
##      run:
##        shell: bash
##    steps:
##      - name: Checkout
##        uses: actions/checkout@v2
##      - name: 'Terraform Format'
##        uses: hashicorp/terraform-github-actions@v3
##        with:
##          tf_actions_version: "latest"
##          tf_action_subcommand: 'fmt'
##          tf_action_working_dir: "./terraform"
##      - name: 'Terraform Init'
##        uses: hashicorp/terraform-github-actions@v3
##        with:
##          tf_actions_version: "latest"
##          tf_action_subcommand: 'init'
##          tf_action_working_dir: "./terraform"
##      - name: 'Terraform plan'
##        uses: hashicorp/terraform-github-actions@v3
##        with:
##          tf_actions_version: "latest"
##          tf_action_subcommand: 'plan'
##          tf_action_working_dir: "./terraform"
##      - name: 'Terraform Apply'
##        uses: hashicorp/terraform-github-actions@v3
##        with:
##          tf_actions_version: "latest"
##          tf_action_subcommand: 'apply'
##          tf_action_working_dir: "./terraform"
##
##
##
###name: 'Terraform'
###
###on:
###  push:
###    branches:
###      - main
###    pull_request:
###  jobs:
###    terraform:
###      name: 'Terraform'
###      env:
###        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
###        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
###        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONS_ID }}
###        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
###      runs-on: ubuntu-latest
###      environment: dev
###      defaults:
###        run:
###          shell: bash
###      steps:
###      - name: Checkout
###        uses: actions/checkout@v2
###      - name: 'Terraform Format'
###        uses: hashicorp/terraform-github-actions@master
###        with:
###          tf_actions_version: 0.14.8
###          tf_action_subcommand: 'fmt'
###          tf_action_working_dir: "./terraform"
###      - name: 'Terraform Init'
###        uses: hashicorp/terraform-github-actions@master
###        with:
###          tf_actions_version: 0.14.8
###          tf_action_subcommand: 'init'
###          tf_action_working_dir: "./terraform"
###      - name: 'Terraform plan'
###        uses: hashicorp/terraform-github-actions@master
###        with:
###          tf_actions_version: 0.14.8
###          tf_action_subcommand: 'plan'
###          tf_action_working_dir: "./terraform"
###      - name: 'Terraform Apply'
###        uses: hashicorp/terraform-github-actions@master
###        with:
###          tf_actions_version: 0.14.8
###          tf_action_subcommand: 'apply'
###          tf_action_working_dir: "./terraform"